parameters:
    kilix_app_status.status_collector.class: Kilix\AppStatusBundle\Service\StatusCollectorService

services:
    kilix_app_status.status_collector:
        class: %kilix_app_status.status_collector.class%
